development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/7") %>

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL", "redis://localhost:6379/7") %>
  channel_prefix: rewards_redemption_production
